### ISSUE TITLE
Use jsonwebtoken instead of jwt for auth

### ISSUE THREAD

**Issue by JFortun** [JoeyMckenzie/realworld-rust-axum-sqlx#1]
I propose as an enhancement to use the [jsonwebtoken](https://crates.io/crates/jsonwebtoken) crate instead of the [jwt](https://crates.io/crates/jwt) crate because the jwt crate's last update was two years ago and seems to be unmaintained. 
Also the jsonwebtoken crate is the most used JWT crate at the moment, is actively maintained and is the "standard" for this purpose.
Thanks for your great work!

**Comment by JoeyMckenzie** [comment]
Are you referring to the JWT service implementation? The `jsonwebtoken` crate is currently being used [in that project](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/src/services/utils/jwt_service.rs#L5) to encode/decode as of now. Let me know if I'm misunderstanding the request here, or if you meant using `jwt` in place of `jsonwebtoken`.

**Comment by JFortun** [comment]
> Are you referring to the JWT service implementation? The `jsonwebtoken` crate is currently being used [in that project](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/src/services/utils/jwt_service.rs#L5) to encode/decode as of now. Let me know if I'm misunderstanding the request here, or if you meant using `jwt` in place of `jsonwebtoken`.

I mean the opposite. Use jsonwebtoken in place of jwt for the reasons posted above.

**Comment by JoeyMckenzie** [comment]
I'm not sure I 100% follow the ask here. The project does not use the [jwt](https://crates.io/crates/jwt) crate, it already uses [jsonwebtoken](https://crates.io/crates/jsonwebtoken) as you mention. It's included in the [`conduit-infrastructure` manifest](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/Cargo.toml#L18) and used in the [token service](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/src/services/utils/jwt_service.rs#L5), at least if I'm understanding the crate resolution correctly (which very well could not be the case!)

**Comment by JFortun** [comment]
> I'm not sure I 100% follow the ask here. The project does not use the [jwt](https://crates.io/crates/jwt) crate, it already uses [jsonwebtoken](https://crates.io/crates/jsonwebtoken) as you mention. It's included in the [`conduit-infrastructure` manifest](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/Cargo.toml#L18) and used in the [token service](https://github.com/JoeyMckenzie/realworld-rust-axum-sqlx/blob/main/conduit-infrastructure/src/services/utils/jwt_service.rs#L5), at least if I'm understanding the crate resolution correctly (which very well could not be the case!)

You can see the jwt crate in the dependencies of conduit-core/Cargo.toml.
Maybe I'm also missing something, could totally be the case 😁

**Comment by JoeyMckenzie** [comment]
Ah I see! My misunderstanding, the jwt crate was hiding in the core project manifest. Removed it, wasn't being used anywhere. Thanks for pointing that out!
